//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

pub mod prelude;

pub mod parties;
pub mod party_memberships;
pub mod users;
pub mod wishlist_item_list_assignments;
pub mod wishlist_item_user_fulfillments;
pub mod wishlist_items;
pub mod wishlist_party_assignments;
pub mod wishlists;
