//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wishlist_party_assignments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub wishlist_id: i32,
    pub party_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::parties::Entity",
        from = "Column::PartyId",
        to = "super::parties::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Parties,
    #[sea_orm(
        belongs_to = "super::wishlists::Entity",
        from = "Column::WishlistId",
        to = "super::wishlists::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Wishlists,
}

impl Related<super::parties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Parties.def()
    }
}

impl Related<super::wishlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wishlists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
